### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by ufulu** [bitswired/ai-chat-app#8]
I saw you post on reddit and now I got time to check it out! This is really great. Thanks a lot for sharing! Unfortunately, I am illiterate in JavaScript, I only know Python so I am unable to contribute actively but was wondering if you could add the following features:

- Option to edit the templates
- Change the used model and fine tune the model settings

**Comment by jimzer** [comment]
[] te

**Comment by jimzer** [comment]
Hi @ufulu these are great ideas! Thanks.
I will create separate issues to track these 2 features.

**Comment by alex-cardenas** [comment]
Adding to this - possible to have "users" with separate chats?

**Comment by jimzer** [comment]
@alex-cardenas Yes definitely possible. 
As soon as I build the authentication system and admin panel to manage your user, the app data will be separated between the different users.
I plan to have it done by the end of the week-end.
Would be cool to have some of you guys test the feature :)

**Comment by alex-cardenas** [comment]
Would be happy to test. I am currently running it in Unraid behind nginx proxy manager and authelia.

**Comment by matthewcmorgan** [comment]
* CTRL+Enter to Submit (or CMD+Enter on MacOs)
* Modal/Alert/Feedback when we get a 500 from OpenAi
* Code Block Support? Maybe using ```<code>``` or `<code>` to differentiate from prose?

**Comment by alex-cardenas** [comment]
@matthewcmorgan I would argue for a straight "Enter" to submit and CTRL/CMD+Enter being new line. In the meantime, I've been doing Tab then Enter for a quick submit.

**Comment by leotulipan** [comment]
Maybe split this out as a separate issue/to do. 

> * Option to edit the templates

You can input a template but you cannot edit it. Workaround is to select it and in the chat mark everything and make a new template and modify the text. Then delete the old template

**Comment by jimzer** [comment]
Hey guys! 
Thanks for all the great ideas. 
I will create separated issues for all your proposal to track the progress.

I will refer to this one.

**Comment by jimzer** [comment]
Template editing will be solved by: #25

**Comment by jimzer** [comment]
@ufulu @alex-cardenas @matthewcmorgan @leotulipan 
I close this issue since we now have separate issues to track the features you requested.
Feel free to comment over there.
