### ISSUE TITLE
Multi-user requirements

### ISSUE THREAD

**Issue by danblaze13** [bitswired/ai-chat-app#9]
Very good job! I have some friends that are located in areas where openai is banned, and I thought if the software had multi-user capabilities, I could make a client that would be easy for them to use.

I wonder if this is in the plan of the roadmap?

**Comment by JamesDAdams** [comment]
Yes it would be really nice with an api call limit option per user 

For example a limit by hours, days, weeks and months.

**Comment by RyzerZ** [comment]
> Very good job! I have some friends that are located in areas where openai is banned, and I thought if the software had multi-user capabilities, I could make a client that would be easy for them to use.
> 
> I wonder if this is in the plan of the roadmap?

I think you could create a portal where your friends can log in, and upon logging in, redirect them to different ports so that each of your friends can access different dockerized instances.

**Comment by jimzer** [comment]
Great idea guys! I didn't think about this use case at first.

The solution of @RyzerZ can be used while I'm getting this feature done.
I'm adding it to the priorities.

**Comment by jimzer** [comment]
@danblaze13 @JamesDAdams  @RyzerZ 

Multi-user support is there: #25 🚀.

I would be glad if you could try the feature and let me know your thoughts!

**Comment by berstend** [comment]
@jimzer great work on #25 👍 

what would be amazing is the ability to limit usage for non-admin accounts for cost control

this could be kept simple at first, like using a single limit that applies to each non-admin account
a token limit per month would be stellar (as that directly translates to API costs) but if "requests" is easier than this would be fine for the time being as well :)
